title: Kokai
description: CLI for your release notes using Conventional Commits.
url: https://joxit.dev/kokai
google_analytics: G-T158HYBVZ2
remote_theme: joxit/joxit.github.io
author: Jones Magloire
twitter:
  username: Joxit
instagram:
  username: jox.it
