title: Kokai
description: CLI for your release notes using Conventional Commits.
url: https://joxit.dev/kokai
google_analytics: UA-99119327-1
remote_theme: joxit/joxit.github.io
author: Jones Magloire
twitter:
  username: Joxit
instagram:
  username: jox.it
