[package]
name = "kokai"
version = "0.1.0"
authors = ["Jones Magloire @Joxit"]
edition = "2018"

[dependencies]
structopt = "^0.3"
regex = "^1.3"
lazy_static = "^1.4"
chrono = "^0.4"

[dependencies.git2]
version = "^0.13"
features = ["vendored-openssl"]
