[package]
name = "kokai"
version = "0.1.0"
authors = ["Jones Magloire @Joxit"]
edition = "2018"

[dependencies]
structopt = { version = "^0.3"}

[dependencies.git2]
version = "^0.13"
features = ["vendored-openssl"]
